#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ $HUSKY_GIT_PARAMS =~ "--amend" && $HUSKY_GIT_PARAMS =~ "--no-edit" ]]; then
  exit 0
fi

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    echo "🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again."; >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "🔨❌ Aborting commit. Your commit message is too long. 🔨❌" >&2
    exit 1
fi

echo "🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻"